login_to_sierra:
  description: >
    Log in into the Madison Reed Dashboard by performing these steps one by one:
    Step 1: Navigate to the url: https://madison-reed.sierra.ai
    Step 2: Enter the email: {email} in the email field
    Step 3: Click the sign in button
  expected_output: >
    Log in into the Madison Reed Dashboard and summarize the result of the login attempt.
  agent: login_agent

summarize:
  description: >
    Identify the title of the most recent chat. The title is the user's first chat to the custom agent.
  expected_output: >
    The title of the most recent chat.
  agent: summarize_agent
