analyze_sierra_conversations:
  description: >
    Complete a full analysis of critical and major issue conversations by following these phases carefully:

    LOGIN PHASE:
    1. Navigate to https://madison-reed.sierra.ai
    2. Enter email: arianna.schwartz@madison-reed.com
    3. Click the sign in button
    4. Use get_verification_code tool to obtain verification code via CLI
    5. Enter the verification code in the "code" field
    6. Click "verify code" button
    7. Verify successful login by confirming dashboard access

    FILTERING PHASE:
    8. Wait for dashboard to fully load
    9. Locate and click the "Status" button
    10. In the dropdown:
        - Select "Major Issues" and verify checkmark appears
        - Select "Critical Issues" and verify checkmark appears
    11. Close the dropdown menu by pressing the escape key or doing the equivalent 
    12. Verify filter application:
        - Wait for the conversations list to update to show only converesations with "critical" or "major" statuses
        - Confirm visible conversations show major/critical icons


    CONVERSATION ANALYSIS PHASE:
    12. Once filters are confirmed active:
        - Locate the most recent conversation
        - Note the title of the conversation. This title is the first message from the user to the chatbot. The message may be long and that is okay, the title of the conversation can be long.
        - Click to view full conversation details
        - Extract complete dialogue between user and agent
        - Analyze the conversation content

    IMPORTANT GUIDELINES:
    - Complete each phase fully before moving to the next
    - Verify success at each step before proceeding
    - Use available tools for all actions - no guessing
    - Wait for page updates to complete
    - If a step fails, retry with variations before reporting failure
    - Maintain clear progress updates
    - Do not yield control until ALL phases are complete

  expected_output: >
    A complete analysis including:
    1. Confirmation of successful login
    2. Verification of active filters (major/critical issues)
    3. Full dialogue from the most recent critical/major issue conversation
    4. Any relevant metadata (timestamp, status, etc.)

  agent: sierra_agent




